import type { Human, Machine } from "./types";

export const MACHINES: Machine[] = [
  { id: "crate", name: "Crate", x: 620, y: 430, w: 168, h: 136, sprite: "/game/props/crate.png", trick: "hide", trickLabel: "Go dark" },
  { id: "fan", name: "Fan", x: 430, y: 300, w: 100, h: 110, sprite: "/game/props/fan.png", trick: "distract", trickLabel: "Rattle" },
  { id: "cabinet", name: "Cabinet", x: 220, y: 220, w: 118, h: 150, sprite: "/game/props/cabinet.png", trick: "hide", trickLabel: "File yourself" },
  { id: "panel", name: "Breaker", x: 200, y: 500, w: 108, h: 124, sprite: "/game/props/panel.png", trick: "cut", trickLabel: "Kill the lights" },
  { id: "lamp", name: "Lamp", x: 860, y: 280, w: 90, h: 110, sprite: "/game/props/lamp.png", trick: "distract", trickLabel: "Flicker" },
  { id: "flood", name: "Floodlight", x: 980, y: 470, w: 130, h: 148, sprite: "/game/props/flood.png", trick: "beam", trickLabel: "Blind them" },
  { id: "phone", name: "Telephone", x: 1080, y: 240, w: 96, h: 88, sprite: "/game/props/phone.png", trick: "distract", trickLabel: "Ring" },
  { id: "typewriter", name: "Typewriter", x: 1220, y: 260, w: 120, h: 96, sprite: "/game/props/typewriter.png", trick: "distract", trickLabel: "Keys" },
  { id: "scope", name: "Oscilloscope", x: 1360, y: 250, w: 118, h: 108, sprite: "/game/props/scope.png", trick: "distract", trickLabel: "Draw a lie" },
  { id: "radio", name: "Radio", x: 1500, y: 280, w: 128, h: 120, sprite: "/game/props/radio.png", trick: "transmit", trickLabel: "Transmit", win: true },
  { id: "battery", name: "Jeep battery", x: 780, y: 740, w: 210, h: 128, sprite: "/game/props/jeep.png", trick: "transmit", trickLabel: "Ride the copper", win: true },
];

export function makeHumans(): Human[] {
  return [
    {
      id: "guard",
      role: "guard",
      x: 900,
      y: 720,
      facing: -Math.PI / 2,
      path: [
        { x: 900, y: 740 },
        { x: 640, y: 520 },
        { x: 980, y: 430 },
        { x: 1320, y: 560 },
        { x: 980, y: 760 },
      ],
      pi: 0,
      stare: 0,
      stunned: 0,
      investigating: null,
      witnessed: false,
      speed: 62,
      range: 228,
      cone: 0.72,
    },
    {
      id: "tech",
      role: "tech",
      x: 1320,
      y: 260,
      facing: 0,
      path: [
        { x: 1320, y: 250 },
        { x: 1480, y: 280 },
        { x: 1400, y: 360 },
        { x: 1180, y: 250 },
      ],
      pi: 0,
      stare: 0,
      stunned: 0,
      investigating: null,
      witnessed: false,
      speed: 48,
      range: 128,
      cone: 1.05,
    },
    {
      id: "colonel",
      role: "colonel",
      x: 280,
      y: 240,
      facing: 0.4,
      path: [
        { x: 250, y: 230 },
        { x: 520, y: 260 },
        { x: 700, y: 400 },
        { x: 420, y: 360 },
      ],
      pi: 0,
      stare: 0,
      stunned: 0,
      investigating: null,
      witnessed: false,
      speed: 40,
      range: 110,
      cone: 0.9,
    },
  ];
}
